/**
 * FileName: Const
 * Author: Mingyoung
 * Date: 2020/6/23 9:44 AM
 * Description: const static variable define
 */
package com.org.msrouter_compiler;

object Const {

    const val PACKAGE = "com.org.msrouter"

    const val kServiceRegisterPackage = "com.org.msrouter"
    const val kProviderSuffixKey = "MSRouter_IRegister"

    const val ROUTE_PROVIDER_NAME = "_MSRouter_IRegister"

    const val MODULE_NAME = "moduleName"


    const val ROUTE_PROVIDER = "com.org.msrouter_api.metamap.IRouteRegister"

    const val METHOD_LOAD = "loadInto"

    const val kAROUTER_VALUE_ENABLE = "enable"
    const val kAROUTER_KEY_GENERATE_DOC_NAME = "AROUTER_MODULE_NAME"


    val APT_PROVIDER_TINT_MSG = """   ***************************************************
                  |   * THIS CODE IS GENERATED BY MSRouter, DO NOT EDIT. *
                  |   ***************************************************
                     |""".trimMargin()

    const val kRT_ANNOTATION_PACKAGENAME = "com.org.msrouter_annotation"
    private const val kAROUTER_FACADE_PACKAGE = "com.alibaba.android.arouter.facade"
    private const val kAROUTER_TEMPLATE_PACKAGE = ".template"

    const val kRT_ANNOTATION_TYPE_AROUTE = "com.alibaba.android.arouter.facade.annotation.Route"
    const val kAROUTER_IPROVIDER =
        kAROUTER_FACADE_PACKAGE + kAROUTER_TEMPLATE_PACKAGE + ".IProvider"
    const val kRT_ANNOTATION_TYPE_FUNC = kRT_ANNOTATION_PACKAGENAME + ".Func"

    const val kOPTION_KEY = "option"
    const val kAROUTER_KEY_MODULE_NAME = "AROUTER_MODULE_NAME"


    // System interface
    const val ACTIVITY = "android.app.Activity"
    const val FRAGMENT = "android.app.Fragment"
    const val FRAGMENT_V4 = "android.support.v4.app.Fragment"
    const val SERVICE = "android.app.Service"
}
